//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteOfFineArt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FINE_ARTSEntities : DbContext
    {
        public FINE_ARTSEntities()
            : base("name=FINE_ARTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<admine> admines { get; set; }
        public virtual DbSet<manager> managers { get; set; }
    }
}
